// Generated by scripts/generate-sdk-deployments.mjs. Do not edit by hand.
export interface RouterDeployment {
  address: string;
  owner: string;
  pool_wasm_hash: string;
  default_protocol_fee: number;
  default_protocol_beneficiary: string;
  permissionless_creation: boolean;
}

export interface TokenRepresentation {
  address: string;
  kind: string;
  initial_balance?: string;
  [key: string]: unknown;
}

export interface TokenDeployment {
  id: string;
  category: "usd" | "eur" | "crypto";
  name: string;
  symbol: string;
  decimals: number;
  soroban: TokenRepresentation;
  sac: TokenRepresentation;
}

export interface PoolDeploymentDefaults {
  swap_fee: number;
}

export interface NetworkDeployment {
  network: string;
  deployed_at?: string;
  source_identity?: string;
  deployer?: string;
  contracts: {
    router?: RouterDeployment;
    tokens?: TokenDeployment[];
    [key: string]: unknown;
  };
  pool_defaults?: PoolDeploymentDefaults;
  [key: string]: unknown;
}

export const deploymentNetworks = ["testnet"] as const;
export type DeploymentNetwork = (typeof deploymentNetworks)[number];
export const deployments: Record<DeploymentNetwork, NetworkDeployment> = {
  "testnet": {
    "network": "testnet",
    "network_passphrase": "Test SDF Network ; September 2015",
    "deployed_at": "2026-09-05T18:54:52Z",
    "source_identity": "perps-testnet",
    "deployer": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
    "contracts": {
      "test_tokens": [
        {
          "label": "sUSDC",
          "address": "CDKFYHC3EPRCZY4DIMCIBQ3PO5QPD6KZFFXNMLS4XENY2QNTZN2KLMRM",
          "name": "Spreadless Test USDC",
          "symbol": "sUSDC",
          "decimals": 7,
          "open_mint": true,
          "supply_cap": null,
          "kind": "custom_soroban_token"
        },
        {
          "label": "sUSDT",
          "address": "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
          "name": "Spreadless Test USDT",
          "symbol": "sUSDT",
          "decimals": 7,
          "open_mint": true,
          "supply_cap": null,
          "kind": "custom_soroban_token"
        },
        {
          "label": "sDAI",
          "address": "CBXN4CMLFVDNVFSGNXFGP5EWI77ISC5KH5UXSDBQETZCJHYHA3KEP4JJ",
          "name": "Spreadless Test DAI",
          "symbol": "sDAI",
          "decimals": 7,
          "open_mint": true,
          "supply_cap": null,
          "kind": "custom_soroban_token"
        }
      ],
      "classic_assets": [
        {
          "label": "SUSD",
          "asset_code": "SUSD",
          "asset_issuer": "GCYFVS3J6JNJLJZ6JVPFCW7IGILIWEFGFPUAFBOBR4PQARR6OIBZHOAU",
          "sac_contract": "CDDE66QMXWVUVEHLA5IRUJBHPJK3RFH6JIXCIJ5S6HOAXAPYR2AIZUWD",
          "issuer_identity": "spreadless-sac-usd-issuer",
          "holder": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
          "decimals": 7,
          "kind": "stellar_classic_asset_with_sac"
        }
      ],
      "liquidity_pool": {
        "label": "4-token-usd-sac-pool",
        "address": "CCAD3EH4P74PVYL3IC6ND7RSV6NYYOMUMNKRNVBJYOVIZP7Z2QS5XTSN",
        "owner": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
        "beneficiary": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
        "tokens": [
          "CBXN4CMLFVDNVFSGNXFGP5EWI77ISC5KH5UXSDBQETZCJHYHA3KEP4JJ",
          "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
          "CDDE66QMXWVUVEHLA5IRUJBHPJK3RFH6JIXCIJ5S6HOAXAPYR2AIZUWD",
          "CDKFYHC3EPRCZY4DIMCIBQ3PO5QPD6KZFFXNMLS4XENY2QNTZN2KLMRM"
        ],
        "token_labels": [
          "sDAI",
          "sUSDT",
          "SUSD_SAC",
          "sUSDC"
        ],
        "amp_factor": 100,
        "swap_fee": 100000,
        "protocol_fee": 0,
        "max_caps": [
          "30000000000000000",
          "30000000000000000",
          "30000000000000000",
          "30000000000000000"
        ],
        "lp_max_supply": "3000000000000000000"
      },
      "previous_pools": [
        {
          "label": "3-token-usd-pool",
          "address": "CD7TRTJF54QP4BDIP4JJIKMBATYP4IZAGZQKGVSXW3VB457IG4RGSAA6",
          "deployed_at": "2026-07-01T14:00:27Z",
          "tokens": [
            "CBXN4CMLFVDNVFSGNXFGP5EWI77ISC5KH5UXSDBQETZCJHYHA3KEP4JJ",
            "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
            "CDKFYHC3EPRCZY4DIMCIBQ3PO5QPD6KZFFXNMLS4XENY2QNTZN2KLMRM"
          ],
          "initial_liquidity": {
            "deposited_each_token": "1000000000000",
            "deposit_result": "300000000000000"
          },
          "last_test_swap": {
            "transaction": "9a4a969290830cb4368483d3555e0ad0f4edf24b50f37ccfbbcc184efc1edf6c",
            "token_in": "CBXN4CMLFVDNVFSGNXFGP5EWI77ISC5KH5UXSDBQETZCJHYHA3KEP4JJ",
            "token_out": "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
            "amount_in": "10000000",
            "amount_out": "9998998",
            "post_swap_reserves": [
              "1000010000000",
              "999990001002",
              "1000000000000"
            ]
          }
        },
        {
          "label": "2-token-usd-pool",
          "address": "CBMJOFJR6NHETIHQWS3YPJGUK267PMHZ6U7HHNXZS66CQNQTI2QPASEV",
          "deployed_at": "2026-07-01T13:41:45Z",
          "tokens": [
            "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
            "CDKFYHC3EPRCZY4DIMCIBQ3PO5QPD6KZFFXNMLS4XENY2QNTZN2KLMRM"
          ],
          "initial_liquidity": {
            "deposited_each_token": "1000000000000",
            "deposit_result": "200000000000000"
          }
        }
      ],
      "router": {
        "address": "CA4VB4SJQAPWBRTMEHCTX7GZ7KC2DGS7PXV6BEZUI3WUOKRGOQ7VCV6M",
        "owner": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
        "pool_wasm_hash": "52dd16bb8eed388a1914922488533a5e4eb2fe69575662b5c7a141e4d7a7ac20",
        "default_protocol_fee": 330000000,
        "default_protocol_beneficiary": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
        "permissionless_creation": true
      },
      "tokens": [
        {
          "id": "abusdc",
          "category": "usd",
          "name": "abUSDC",
          "symbol": "abUSDC",
          "decimals": 7,
          "soroban": {
            "address": "CCCF52BTMLYFGCUZUKV67QUE7DHP3MHVIN7G7UMCBI2TN5R7FB7EG5YT",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBCJWFNOJH2GNYLCBMK7JWOCMQPWO4I6ISQFI75ICMDHBOHJSAATH7B2",
            "asset": "abUSDC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "apusdc",
          "category": "usd",
          "name": "apUSDC",
          "symbol": "apUSDC",
          "decimals": 7,
          "soroban": {
            "address": "CABMCMK4VDPYZYJAHTUSZJMEGNYSE26DNZUV5RDULZP3QOUK3RCVUW4F",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBKQKRSRUN6PEWMZD45CAXCIINFRXCK574QOXVADANJCSXGV7HUAV4L2",
            "asset": "apUSDC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "bnusd",
          "category": "usd",
          "name": "BnUSD",
          "symbol": "BnUSD",
          "decimals": 7,
          "soroban": {
            "address": "CA5OEH6LG73HQOGD7SOP5NQSKU3IFRUQSJM453ZUYZO5AKD2BUXU4IHR",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CCTNR5YC4YZ6QW3TU3TVZCVR23PUC6IEATZE4Q7BVG7KFXNIB2LDNK5D",
            "asset": "BnUSD:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "btc",
          "category": "crypto",
          "name": "BTC",
          "symbol": "BTC",
          "decimals": 7,
          "soroban": {
            "address": "CDWEAOXHL6FRJNUMHRXWWJ2QTQAZHSMITVQWV33G6QXCMDUQET4WIEL6",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CDOXMVS4VHXSOHOLBWC37K7UGO6ECU46URCMXMUI2U4KFDZUF2K6JOHO",
            "asset": "BTC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "eth",
          "category": "crypto",
          "name": "ETH",
          "symbol": "ETH",
          "decimals": 7,
          "soroban": {
            "address": "CAX2IOWT3LXA52Y7WXV6VMULGZ46I545QSNW2DTSVIISIMMIFB76KXMQ",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CAHMVFMRJP3EUMR74TT24JXO5TGX37R22N63XL6YSKIXKWH42UHZVIJF",
            "asset": "ETH:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "eurc",
          "category": "eur",
          "name": "EURC",
          "symbol": "EURC",
          "decimals": 7,
          "soroban": {
            "address": "CACQCZVWAOVFUHSAE7RTUNKEGGN4YVPBVEJ47OOYLHOC2NCMBH36RRFA",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CCJSAHXNWX6RJKZDYAQTZQ4Z2PRYUF6K5RC6TQIZ35HWDDFWT3B7N2TI",
            "asset": "EURC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "eurx",
          "category": "eur",
          "name": "EURx",
          "symbol": "EURx",
          "decimals": 7,
          "soroban": {
            "address": "CCJG4Y6FQTDZCCACSD3YQAYQCQLTRWLNC7XUURHQDQJ2I3JFXIOAIQZR",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CB7REND3PSSRB4QGBKT72WBZ3SMTRE2JMVI4L4DO2I7QAAY6C3PQSQSE",
            "asset": "EURx:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "ousd",
          "category": "usd",
          "name": "oUSD",
          "symbol": "oUSD",
          "decimals": 7,
          "soroban": {
            "address": "CBG6LSYHUNBEYRUAEREKS6D7TH752S4OIKROPFN4ZT6K5RJ2X5OIDCSG",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CAPNOLF7DAA7YL2WWGKFLP37SMCEXJWHIDVWYDPHQKCQZUZ25O3XCQ4U",
            "asset": "oUSD:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "pom",
          "category": "usd",
          "name": "POM",
          "symbol": "POM",
          "decimals": 7,
          "soroban": {
            "address": "CBP4VFKL7TJDODDBYLOX5OZDDL6QZBHD4LFAFNYNOAH6LKT5NCI4NM64",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CA3PCQMIFS6YIBMGOY7WY6QZMRYV6IPYYVCPZH3M5B7T2CV6GP6JWY5R",
            "asset": "POM:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "rlusd",
          "category": "usd",
          "name": "RLUSD",
          "symbol": "RLUSD",
          "decimals": 7,
          "soroban": {
            "address": "CBUNEWTFCY7LSWZOZECPDSAODO7EGH4DYBZS55EX7JRPOEFHMF2XJW2E",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBXSZRWOA2DOKQRP2667FV3Y6EINTUABEBO7Q6HBBUHPT74NYPVKOS6T",
            "asset": "RLUSD:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "solvbtc",
          "category": "crypto",
          "name": "SolvBTC",
          "symbol": "SolvBTC",
          "decimals": 7,
          "soroban": {
            "address": "CCFMQ4452IA6M2Q4YNGRKACJY3R5UPIYI5XUU56WF5MLJF75QHDA3RDL",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CB5YAZKUQYK4ZUMLPPIXPFHIDWMB2YPGXTAVPJCB4SNIZGWZUCIRKIO7",
            "asset": "SolvBTC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdc",
          "category": "usd",
          "name": "USD Coin",
          "symbol": "USDC",
          "decimals": 7,
          "soroban": {
            "address": "CD2Z4HLXN6726L7B5NYYK2YELFV4EVWLAT5W4KRJHL73IERVXXVR22ZO",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CCECUYZHZWFLVNY56XMEREDFHOCERKHAVKYIRSBRYQ5JZFVMBMGRLA65",
            "asset": "USDC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdglo",
          "category": "usd",
          "name": "USDGLO",
          "symbol": "USDGLO",
          "decimals": 7,
          "soroban": {
            "address": "CB7BFIYHMDVTF7PYBZH3AQE66TR7LISVVXGWZ6ELI44BCAPOYVYK4DH4",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBCMZ7EFHLF36E42LODRTPX6PQSPXLFHLTWXLBAEHTRKY5JIT6KXC7QU",
            "asset": "USDGLO:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdm",
          "category": "usd",
          "name": "USDM",
          "symbol": "USDM",
          "decimals": 7,
          "soroban": {
            "address": "CDDT6MUPQ2RCC2TBNIJYRV3HC2BPFH4GC66Z36JCJQE4YCCIR55H7H3U",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBYREATLQEN535EQC4D6DBQFWQJVUOMHDYNJN53HHPP6FA22FF6GUL5D",
            "asset": "USDM:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdm1",
          "category": "usd",
          "name": "USDM1",
          "symbol": "USDM1",
          "decimals": 7,
          "soroban": {
            "address": "CBP7QXKBROFKJWGEF3ZQ5S3ASALEVI3LSCYZ4EYSTS5I3EVWVHD3LSGT",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CA22J2TDKHWI5KZYCTL3MXKYVKTFTYISWHUR3RKQOOWC677AMZUAPAPY",
            "asset": "USDM1:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdp",
          "category": "usd",
          "name": "USDP",
          "symbol": "USDP",
          "decimals": 7,
          "soroban": {
            "address": "CD6VUH76JBC34P42GUH4BHD4UCKA6TMK3FXBXQC5QBG5SS5GRJWQNVAC",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CDMHPLIOKL6UREOMJ4NXVC67Q74AFVS456SAV4WSNEK2LTB7ONEX3IOZ",
            "asset": "USDP:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "usdt0",
          "category": "usd",
          "name": "USDT0",
          "symbol": "USDT0",
          "decimals": 7,
          "soroban": {
            "address": "CBBYP4J5JXO7ZTRZO4RU3T4MYO53J2YHRWV2FJIVJDQXXMOHJPUKSHVJ",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBOO32ELJOFG6BU3FJWLCFT55TRE5WDCWUUPCUWJDYRF4VCPE4TL3HDR",
            "asset": "USDT0:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "xcr",
          "category": "eur",
          "name": "XCR",
          "symbol": "XCR",
          "decimals": 7,
          "soroban": {
            "address": "CBB5XNCVDL6DLUY5WSSMXPRX7ZGPQ5USPVVRMY7DJOZEAXFUZYAOYILF",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CC6C7XOQ7YDGJ5CDJNZHUAS3UAANCIJTWHRH772F5HNJPXB4LIA2P374",
            "asset": "XCR:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "xlm",
          "category": "crypto",
          "name": "XLM",
          "symbol": "XLM",
          "decimals": 7,
          "soroban": {
            "address": "CBWAT5MWPEZVZQAXH5NHGGF3FKUY62GQSQVAEUCGPRBPHSF45QYAU7AX",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
            "asset": "native",
            "issuer": null,
            "issuer_identity": null,
            "kind": "native_stellar_asset_with_sac",
            "initial_balance": "network-funded"
          }
        },
        {
          "id": "xrp",
          "category": "crypto",
          "name": "XRP",
          "symbol": "XRP",
          "decimals": 7,
          "soroban": {
            "address": "CAUBDT5XVJF4C3XTLIZPFZHZ6JG2N3UHUYBHPJNGQHBBQUS6KHDTC4Q7",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBKDCO73A4QOT6FVOXWNKEGXLJC73KTBIA3BPQB55VI7UF6GNCN3G7YK",
            "asset": "XRP:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "xsolvbtc",
          "category": "crypto",
          "name": "xSolvBTC",
          "symbol": "xSolvBTC",
          "decimals": 7,
          "soroban": {
            "address": "CDFNZVN3ODKWLMSU3SGAZOCRJABWLZDUSUO4LUKW4FS2XL63RGZFMUD4",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBY4TUCXWS5CS3C6CXSBC67BSU5IVEYU4SNNEDCRA6B6J6XGTGMZ2DDL",
            "asset": "xSolvBTC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "ybtc",
          "category": "crypto",
          "name": "yBTC",
          "symbol": "yBTC",
          "decimals": 7,
          "soroban": {
            "address": "CAOV3NBZP637QXNM3ZVXI3Z77PHZWIQGDFDACYOAGCFFKLW5ORQ4JNBX",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBSRGAAPSY37H3362B6PYDQSN7XVRJDH56IHLFNRNAR42GBHCOWRAOAJ",
            "asset": "yBTC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "yeth",
          "category": "crypto",
          "name": "yETH",
          "symbol": "yETH",
          "decimals": 7,
          "soroban": {
            "address": "CDOWWMOCQRT6UTHHNSNBHWM5VET5KPLOJLUUQ5II57WJRKAYVYDMM4YN",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CC7U7YQXOOQSYGVPGLWVE55GQI3MWWQNH4JHDXPMTUHCYJTAP4NWC4LG",
            "asset": "yETH:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "yusdc",
          "category": "usd",
          "name": "yUSDC",
          "symbol": "yUSDC",
          "decimals": 7,
          "soroban": {
            "address": "CCQ4KSBII5J3WPNIW6H4SRG4NDYMXL3Q64BFUO6H7WGEU3D45J24BMQO",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CCHZ33LHJ77GRBT4I6ANOFKYM5DQCY5KN3QBNUUXU2YQFA3K3FBZWAP7",
            "asset": "yUSDC:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "yxlm",
          "category": "crypto",
          "name": "yXLM",
          "symbol": "yXLM",
          "decimals": 7,
          "soroban": {
            "address": "CBUW6BKN2ADRZBCAP6HWEID6VAADZCQOUETYSIPKXL5G3EATPS5TXODM",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CBWNFXC5J5MYL46SUM6DYSC3QLXVVZD5T3P5LSHENXK7O3DNDL724LF5",
            "asset": "yXLM:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "yxrp",
          "category": "crypto",
          "name": "yXRP",
          "symbol": "yXRP",
          "decimals": 7,
          "soroban": {
            "address": "CAYVBFOJZ4XMFJ2H6JRSPTEQJEKZQMKQATSI5OHNEAVHE4ORD5AWD4WN",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CDZDTGAPAYZJKAIJUUCCRLIVQ7ICRE2T3NAQDOFLUVBUO4AKN7OXXHJQ",
            "asset": "yXRP:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        },
        {
          "id": "zusd",
          "category": "usd",
          "name": "ZUSD",
          "symbol": "ZUSD",
          "decimals": 7,
          "soroban": {
            "address": "CD5LGJIXSRRVCLEXUEYNDC7KLDJABJFZ6QXMYXA5VIOHJVRA3BBKY2ID",
            "kind": "custom_soroban_token",
            "open_mint": true,
            "initial_balance": "1000000000000"
          },
          "sac": {
            "address": "CAXN625SZQ7KADRKQNXBP45IMV3TEP6CJXKFEBMBAZ66HDWQFGCVHU7Y",
            "asset": "ZUSD:GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534",
            "issuer_identity": "spreadless-testnet-asset-issuer",
            "kind": "stellar_classic_asset_with_sac",
            "initial_balance": "1000000000000"
          }
        }
      ],
      "token_catalog": {
        "source": "config/tokens.json",
        "holder": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
        "sac_issuer": "GCING6MWLKCAUEQG3ZMIDR2YZH2GG2QANN32DM5KJBIIRWRWTGIQP534"
      }
    },
    "pool_defaults": {
      "swap_fee": 10000000
    },
    "initial_liquidity": {
      "provider": "GBQNJHJJRTKU43GOW34BQXLMTRZFOZERDGQPBUZGXTJK3HQEEDXXL73B",
      "minted_each_token": "1000000000000",
      "deposited_each_token": "1000000000000",
      "deposit_result": "400000000000000"
    },
    "last_test_swap": {
      "transaction": "67f92aea85b19c60d6441629ec507b5530bf8f7c71be49c162c3709836911fe1",
      "token_in": "CDDE66QMXWVUVEHLA5IRUJBHPJK3RFH6JIXCIJ5S6HOAXAPYR2AIZUWD",
      "token_out": "CB2NS6KYG5ZBHHVKXCHYWLRRH4AKFXNWRYNSQTKNFW23CAY4SGSQVG75",
      "amount_in": "10000000",
      "amount_out": "9998998",
      "post_swap_reserves": [
        "1000000000000",
        "999990001002",
        "1000010000000",
        "1000000000000"
      ]
    },
    "notes": [
      "The custom test token mint(to, amount) entrypoint is intentionally open and uncapped.",
      "The SUSD token is a testnet Stellar classic asset wrapped by a SAC contract.",
      "Pool token order is canonical and may differ from the display labels above.",
      "The active liquidity_pool is the 4-token USD-variant pool including the SUSD SAC."
    ]
  }
};
export type Deployment = NetworkDeployment;
